title: Ganesh Pimpale
url: "ganeshpimpale.github.io"
baseurl: "/home"

markdown: kramdown
#ins_logo: ""

tracking_id: #

footer: no
footer_url: "https://github.com/GaneshPimpale"
footer_text: "© Ganesh Pimpale, MIT Licensed, Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/home/"
 - name: "Resume"
   link: "_pdfs/11-29-2021RES.pdf"
 - name: "Contact"
   link: "contact"
